name: iOS Build

on:
  push:
    branches: [ "main", "tech" ]
  pull_request:
    branches: [ "main", "tech" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install npm dependencies
        run: npm install

      - name: Install CocoaPods
        run: cd ios && pod install

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace Food_Delivery_App.xcworkspace \
            -scheme Food_Delivery_App \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -derivedDataPath ${{ github.workspace }}/derivedData \
            build

      - name: Zip the App
        run: |
          cd ${{ github.workspace }}/derivedData/Build/Products/Release-iphonesimulator
          zip -r Food_Delivery_App.zip Food_Delivery_App.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: derivedData/Build/Products/Release-iphonesimulator/Food_Delivery_App.zip